### ISSUE TITLE
Is this code applicable to camden also ?

### ISSUE THREAD

**Issue by pradeepkusingh** [ryanjbaxter/zuul-retryer#2]
I read somewhere that in Camden we are using Spring retry instead of ribbon and zuul retry. Does this code still applicable in Camden  or do I need to make some changes ?

**Comment by ryanjbaxter** [comment]
No it does not, it only applies to Brixton.  In Brixton we use the Ribbon RestClient to make HTTP requests.  In Camden we use an Apache HTTP client.  In Camden I am working on simplifying things so we consistently use Spring Retry across Spring Cloud.
