### ISSUE TITLE
Post calls 404/405 retries

### ISSUE THREAD

**Issue by sheiktajudeen** [ryanjbaxter/zuul-retryer#3]
When i try to make the post call, on the retry the request json is not getting sent properly and the call is not being retried when the status is 404/405. 

I am using SBA 1.4.1 and CAMDEN.RELEASE.

Can you please advise on this?

**Comment by ryanjbaxter** [comment]
Does this have anything to do with this project?  Sounds like you might want to open an issue in Spring Cloud.
