### ISSUE TITLE
Is ZULL retry will work in Gaia environment only ?

### ISSUE THREAD

**Issue by manohar427** [ryanjbaxter/zuul-retryer#5]
Hi I have a question related to zuul retry .. i am trying to do zuul retry changes related an application which is lying under non- gai environment,retry mechanism is not working and same code is working in Gaia environment.My ZUUl application is pointing to gaia environment urls.

Is zuul retry will work only from Gaia environment ?

**Comment by ryanjbaxter** [comment]
I am not sure what a Gaia environment is.
